### ISSUE TITLE
Timestamp? 

### ISSUE THREAD

**Issue by Knigge** [jdanders/ovms-leaf-home-assistant-yaml#1]
Hi and thanks for creating this!

I have now implemented it with my own HA setup, and I am listening on MQTT from the OVMS v3 server. I encounter what you also might have seen from your usage, that it is difficult to know if the data is valid. 

I am uncertain where to put this code, that you list in the readme. Could you show me an example of where it is implemented? every place i put it results in errors :)

```
This repo connects availability of everything to the connected state of the v3 server. This is useful if you want to know if data is valid. My approach is to add the event sensor to my Home Assistant page with a last updated indicator.
To add availability, add this to each sensor:

  availability:
      topic: "ovms/[mqtt-user]/[CAR-ID]/metric/s/v3/connected"
      payload_available: "yes"
      payload_not_available: "no"
      
```
Thanks again! Great resource

**Comment by jdanders** [comment]
Take a look at the repository I linked in the readme: https://github.com/mdallaire/ovms-hass-configs/blob/main/mqtt.yaml
